### ISSUE TITLE
Stopped working after 1.10.1

### ISSUE THREAD

**Issue by oae** [lunaryorn/gnome-search-providers-vscode#33] opened 2022-11-26 14:56 UTC
After the update, vscode projects are missing from the search. And in journlctl I have the following error;

```
Nov 26 17:52:25 archer gnome-shell[1638]: Received error from D-Bus search provider code.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: Unknown object '/de/swsnr/searchprovider/vscode/official/code'
Nov 26 17:52:26 archer gnome-shell[1638]: Received error from D-Bus search provider code.desktop: Gio.DBusError: GDBus.Error:org.freedesktop.DBus.Error.UnknownObject: Unknown object '/de/swsnr/searchprovider/vscode/official/code'
```

**Comment by lunaryorn** [comment] 2022-11-26 16:02
I can't reproduce this.  Take a look at the logs of this service itself; perhaps there's some indication of a problem.

In any case, this doesn't affect me, and since I cannot even reproduce it, I'm afraid I cannot help you.  You'll have to debug and fix this yourself.  Pull requests welcome 🙂 

I'm closing this issue since it's not actionable for me.

**Closed by lunaryorn** 2022-11-26 16:02 UTC
